version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: <your_user>
      POSTGRES_PASSWORD: <your_password>
      POSTGRES_DB: <your_db>
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine

volumes:
  postgres_data:
